EximBd960/Models/Applicant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace EximBd960.Models
{
    public class Applicant
    {
        [Key]
        public int ApplicantId { get; set; }

        [Display(Name = "Enrolled By: ")]
        public int UserId { get; set; }
        [ForeignKey("UserId")]
        public virtual User User { get; set; }

        [Display(Name = "Enroll Date: ")]
        // [Required(ErrorMessage = "Enter EntryDate Please")]
        public DateTime? EntryDate { get; set; }

        [Display(Name = "Applicant's Name: ")]
       // [Required(ErrorMessage = "Name Cant be empty")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Password length should be between 3 to 50.")]
        public string ApplicantName { get; set; }

        [Display(Name = "Upload image: ")]
        [Column(TypeName = "varchar(MAX)")]
        //[Required(ErrorMessage = "Upload Image please")]
        public string ImageURL { get; set; }

        [Display(Name = "Passport No.: ")]
        //[Required(ErrorMessage = "Enter Passport number.")]
        public string PassportNo { get; set; }

        [Display(Name = "Passport Validity: ")]
        //[Required(ErrorMessage = "Enter passport validity")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? PassportValidity { get; set; }

        [Display(Name = "Birth Place: ")]
        //[Required(ErrorMessage = "Enter birth place.")]
        public string BirthPlace { get; set; }

        [Display(Name = "Applicant's Age: ")]
        //[Required(ErrorMessage = "Enter Age.")]
        public int Age { get; set; }

        [Display(Name = "Number of Child: ")]
        //[Required(ErrorMessage = "Enter the number of child.")]
        public int Child { get; set; }

        [Display(Name = "Mobile No.: ")]
        [Required(ErrorMessage = "Enter Mobile number.")]
        public string MobileNo { get; set; }

        [Display(Name = "Country: ")]
        public int? CountryId { get; set; }
        [ForeignKey("CountryId")]
        public virtual Country Country { get; set; }

        [Display(Name = "Company: ")]
        public int? CompanyId { get; set; }
        [ForeignKey("CompanyId")]
        public virtual Company Company { get; set; }

        [Display(Name = "Agents Name: ")]
        public int AgentId { get; set; }
        [ForeignKey("AgentId")]
        public virtual Agent Agent { get; set; }

        [Display(Name = "Medical Status: ")]
        //[Required(ErrorMessage = "Enter Medical Status.")]
        public string MedicalStatus { get; set; }

        [Display(Name = "TC Status: ")]
        //[Required(ErrorMessage = "Enter Tc status.")]
        public string TcStatus { get; set; }

        [Display(Name = "PC Status: ")]
        //[Required(ErrorMessage = "Enter pc status.")]
        public string PcStatus { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "CV Date: ")]
        //[Required(ErrorMessage = "Enter CV date.")]
        public DateTime? CvDate { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Visa Date: ")]
        public DateTime? VisaDate { get; set; }

        [Display(Name = "Agreement Date: ")]
        //[Required(ErrorMessage = "Enter agreement date.")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? AgreementDate { get; set; }

        [Display(Name = "Finger: ")]
        public string Finger { get; set; }

        [Display(Name = "Embassy Report: ")]
        public string EmbassyReport { get; set; }

        [Display(Name = "Manpower: ")]
        public string Manpower { get; set; }

        [Display(Name = "Status: ")]
        public string Status { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Flight Date: ")]
        public DateTime? FlightDate { get; set; }

        [Display(Name = "Note: ")]
        public string Note { get; set; }

        public int? JobId { get; set; }
        [ForeignKey("JobId")]
        public virtual Job Job { get; set; }
    }
}

EximBd960/Controllers/ApplicantsController.cs
using System;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EximBd960.Models;

namespace EximBd960.Controllers
{

	public class ApplicantsController : Controller
    {
        private Eximbd960DbContext db = new Eximbd960DbContext();

        [AllowAnonymous]
        // GET: Applicants
        public ActionResult Index()
        {
            var applicants = db.Applicants.Include(a => a.Agent).Include(a => a.Company).Include(a => a.Country).Include(a => a.User);
            return View(applicants.ToList());
        }
        public ActionResult Index1()
        {
            var applicants = db.Applicants.Include(a => a.Agent).Include(a => a.Company).Include(a => a.Country).Include(a => a.User);
            return View(applicants.ToList());
        }
        [Authorize(Roles = "Moderator")]
        // GET: Applicants/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Applicant applicant = db.Applicants.Find(id);
            if (applicant == null)
            {
                return HttpNotFound();
            }
            return View(applicant);
        }

        [Authorize(Roles = "Moderator")]
        // GET: Applicants/Create
        public ActionResult Create()
        {
            ViewBag.AgentId = new SelectList(db.Agents, "AgentId", "AgentName");
            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "CompanyName");
            ViewBag.CountryId = new SelectList(db.Countries, "CountryId", "CountryName");
            ViewBag.JobId = new SelectList(db.Jobs, "JobId", "JobType");
          

            return View();
        }

        // POST: Applicants/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ApplicantId,ApplicantName,PassportNo,PassportValidity,BirthPlace,Age,Child,MobileNo,CountryId,CompanyId,AgentId,MedicalStatus,Note,JobId,ImageURL")] Applicant applicant,HttpPostedFileBase imageUpload)
        {
            if (ModelState.IsValid)
            {
                string path = ImageUpload(imageUpload);
                if (path.Equals("-1"))
                {

                }
                else
                {
                    applicant.ImageURL = path;
                    applicant.EntryDate = DateTime.Now;
                    //string user = SignInManagerExtensions.AuthenticationResponseGrant.Identity.GetUserId();
                    //  applicant.UserId =int.Parse(user);
                    User user = db.Users.FirstOrDefault(x => x.UserName == User.Identity.Name);
                    applicant.UserId = user.UserId;
                    db.Applicants.Add(applicant);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }

            ViewBag.AgentId = new SelectList(db.Agents, "AgentId", "AgentName", applicant.AgentId);
            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "CompanyName", applicant.CompanyId);
            ViewBag.CountryId = new SelectList(db.Countries, "CountryId", "CountryName", applicant.CountryId);
            ViewBag.JobId = new SelectList(db.Jobs, "JobId", "JobType",applicant.JobId);
           

            return View(applicant);
        }

        
        //public string UploadImage(HttpPostedFileBase file)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            if (file != null)
        //            {
        //                string path = Path.Combine(Server.MapPath("~/Content/ApplicantUpload"), Path.GetFileName(file.FileName));
        //                file.SaveAs(path);
        //            }
        //            return  "File Uploaded successfully";
        //        }
        //        catch (Exception e)
        //        {
        //           return  "Error while uploading";
        //        }
        //    }
        //    else
        //    {
        //        return "Error while uploading";
        //    }
        //}


        public string ImageUpload(HttpPostedFileBase imgFile)
        {
            Random r = new Random();
            string path = "-1";
            int random = r.Next();
            if(imgFile!=null && imgFile.ContentLength>0)
            {
                string extension = Path.GetExtension(imgFile.FileName);
                if(extension.ToLower().Equals(".jpg") || extension.ToLower().Equals(".jpeg") || extension.ToLower().Equals(".PNG"))
                {
                    try
                    {
                        path = Path.Combine(Server.MapPath("~/Content/ApplicantUpload"),random + Path.GetFileName(imgFile.FileName));
                        imgFile.SaveAs(path);
                        path= "~/Content/ApplicantUpload/"+ random + Path.GetFileName(imgFile.FileName);
                    }
                    catch(Exception ex) 
                    {
                        path = "-1";
                    }
                }
            }
            else
            {
                Response.Write("<script>alert('Only jpg ,jpeg or png formats are acceptable....'); </script>");
            }
            return path;
        }

        [Authorize(Roles = "Moderator")]
        // GET: Applicants/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Applicant applicant = db.Applicants.Find(id);
            if (applicant == null)
            {
                return HttpNotFound();
            }
            ViewBag.AgentId = new SelectList(db.Agents, "AgentId", "AgentName", applicant.AgentId);
            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "CompanyName", applicant.CompanyId);
            ViewBag.CountryId = new SelectList(db.Countries, "CountryId", "CountryName", applicant.CountryId);
            ViewBag.JobId = new SelectList(db.Jobs, "JobId", "JobType", applicant.JobId);

            return View(applicant);
        }

        [Authorize(Roles = "Moderator")]
        // POST: Applicants/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ApplicantId,UserId,EntryDate,ApplicantName,ImageURL,PassportNo,PassportValidity,BirthPlace,Age,Child,MobileNo,CountryId,CompanyId,AgentId,MedicalStatus,TcStatus,PcStatus,CvDate,VisaDate,AgreementDate,Finger,EmbassyReport,Manpower,Status,FlightDate,Note")] Applicant applicant)
        {
            if (ModelState.IsValid)
            {
                db.Entry(applicant).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AgentId = new SelectList(db.Agents, "AgentId", "AgentName", applicant.AgentId);
            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "CompanyName", applicant.CompanyId);
            ViewBag.CountryId = new SelectList(db.Countries, "CountryId", "CountryName", applicant.CountryId);
            ViewBag.JobId = new SelectList(db.Jobs, "JobId", "JobType", applicant.JobId);

            return View(applicant);
        }

        [Authorize(Roles = "Moderator")]
        // GET: Applicants/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Applicant applicant = db.Applicants.Find(id);
            if (applicant == null)
            {
                return HttpNotFound();
            }
            return View(applicant);
        }

        [Authorize(Roles = "Moderator")]
        // POST: Applicants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Applicant applicant = db.Applicants.Find(id);
            db.Applicants.Remove(applicant);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

		public ActionResult ApplicantINMedical()
		{
		    var applicant = db.Applicants.Where(x => (x.MedicalStatus == "Need Medical") || (x.MedicalStatus == "In Medical")).ToList();
			ViewBag.Country = new SelectList(db.Countries, "CountryId", "CountryName");
			ViewBag.Company = new SelectList(db.Companies, "CompanyId", "CompanyName");
			ViewBag.Agents = new SelectList(db.Agents, "AgentId", "AgentName");
			return View(applicant);
		}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EximBd960/Views/Applicants/ApplicantINMedical.cshtml
@model IEnumerable<EximBd960.Models.Applicant>
@{
	ViewBag.Title = "ApplicantINMedical";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="panel panel-body">
	<div class="row">
		<div class="col-md-4">
			@Html.DropDownList("Country", null, "--Select Country--", htmlAttributes: new { @class = "form-control" })
		</div>
		<div class="col-md-4">
			@Html.DropDownList("Company", null, "--Select Company--", htmlAttributes: new { @class = "form-control" })
		</div>
		<div class="col-md-4">
			@Html.DropDownList("Agents", null, "--Select Agent--", htmlAttributes: new { @class = "form-control" })
		</div>
	</div>
</div>

@foreach (var applicants in Model)
{
	<div class="panel panel-body row" style="background-color:#595959" >
		@*<div class="row">
			<div class="col-sm-4">
				<img src=@Url.Content(@applicants.ImageURL)  width="100" height="100" alt="Applicant Name"/>
               
            </div>
			<div class="col-sm-4">
				@Html.Label("Name", htmlAttributes: new { @class = "control-label col-md-2" })
				@Html.DisplayFor(modelItem=>applicants.ApplicantName,new {@class="col-md-2" })
			</div>
		</div>*@
		<div class="col-md-9 row" >
			<div class="col-md-3">
				<img src=@Url.Content(@applicants.ImageURL) width="150" height="150" alt="Applicant Name" />
			</div>
			<div class="col-md-6">
				<div class="row">
					<div class="col-md-2">
						<h3 class="text-capitalize font-weight-bold">@applicants.ApplicantName</h3>
					</div>
					<div class="col-md-4 row">
						<div class="col-md-1">
							Medical Status:
						</div>
						<div class="col-md-3">
							@applicants.MedicalStatus
						</div>
					</div>
					
				</div>
			</div>
		</div>
		<div class="col-md-3 bg-danger">

		</div>
	</div>
}

EximBd960/Views/Applicants/Create.cshtml
@model EximBd960.Models.Applicant

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <div class="panel panel-primary ">
        <h2>Create Applicant</h2>

        <div class="panel-body bg-primary">
            @using (Html.BeginForm("Create", "Applicants", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                    <div class="row ">
                        <div class="col-sm-1"></div>
                        <div class="form-group  ">
                            @Html.LabelFor(model => model.ApplicantName, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.ApplicantName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ApplicantName, "", new { @class = "text-danger" })
                            </div>
                            @Html.LabelFor(model => model.ImageURL, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                <input type="file" name="imageUpload" id="imageUpload" class="btn btn-info" />

                                @Html.ValidationMessageFor(model => model.ImageURL, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-1"></div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.PassportNo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.PassportNo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PassportNo, "", new { @class = "text-danger" })
                            </div>

                            @Html.LabelFor(model => model.PassportValidity, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.PassportValidity, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PassportValidity, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-1"></div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.BirthPlace, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.BirthPlace, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.BirthPlace, "", new { @class = "text-danger" })
                            </div>

                            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-1"></div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Child, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.Child, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Child, "", new { @class = "text-danger" })
                            </div>

                            @Html.LabelFor(model => model.MobileNo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-1"></div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.CountryId, "Country", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.DropDownList("CountryId", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.CountryId, "", new { @class = "text-danger" })
                            </div>

                            @Html.LabelFor(model => model.CompanyId, "Company", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.DropDownList("CompanyId", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.CompanyId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-1"></div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.AgentId, "Agent", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.DropDownList("AgentId", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.AgentId, "", new { @class = "text-danger" })
                            </div>

                            @Html.LabelFor(model => model.JobId, "Job", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.DropDownList("JobId", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.JobId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-1"></div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.MedicalStatus, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                <select id="MedicalStatus" name="MedicalStatus" class="form-control">
                                    <option value="Need Medical">Need Medical</option>
                                    <option value="In Medical">In Medical</option>
                                    <option value="Medical Fit">Medical Fit</option>
                                    <option value="Need Gamca">Need Gamca</option>
                                    <option value="In Gamca">In Gamca</option>
                                    <option value="Gamca Fit">Gamca Fit</option>

                                </select>
                            </div>
                            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class='btn btn-success pull-right' />

                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EximBd960/Views/Applicants/Delete.cshtml
@model EximBd960.Models.Applicant

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Applicant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Agent.AgentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Agent.AgentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country.CountryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country.CountryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EntryDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EntryDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicantName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicantName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageURL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PassportNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PassportNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PassportValidity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PassportValidity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthPlace)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthPlace)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Child)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Child)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MobileNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MobileNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MedicalStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MedicalStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TcStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TcStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PcStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PcStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CvDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CvDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VisaDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VisaDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgreementDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgreementDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Finger)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Finger)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmbassyReport)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmbassyReport)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Manpower)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manpower)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FlightDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FlightDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EximBd960/Views/Applicants/ExperiencedEmployee.cshtml
@model EximBd960.Models.ExperiencedApplicant

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ExperiencedApplicant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ApplicantId, "ApplicantId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ApplicantId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ApplicantId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Experience, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Experience, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Experience, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>